infrastructure/ScheduledScaling/README.md, infrastructure/ScheduledScaling/ScheduledScaling.template.json
=> Adding scheduled-scaling-cfn

python/DatastreamKafkaConnector/README.md, python/DatastreamKafkaConnector/application_properties.json, python/DatastreamKafkaConnector/datastream-kafka-connector-example.py, python/FirehoseSink/README.md, python/FirehoseSink/application_properties.json, python/FirehoseSink/pom.xml, python/FirehoseSink/streaming-firehose-sink.py, python/GettingStarted/README.md, python/GettingStarted/application_properties.json, python/GettingStarted/getting-started.py, python/README.md, python/SlidingWindows/README.md, python/SlidingWindows/application_properties.json, python/SlidingWindows/sliding-windows.py, python/StreamingFileSink/README.md, python/StreamingFileSink/application_properties.json, python/StreamingFileSink/streaming-file-sink.py, python/TumblingWindows/README.md, python/TumblingWindows/application_properties.json, python/TumblingWindows/tumbling-windows.py, python/UDF/README.md, python/UDF/application_properties.json, python/UDF/udf.py, python/data-generator/README.md, python/data-generator/stock.py
Port of all PyFlink examples, enriching docs
=> Port Python examples

java/Windowing/README.md, java/Windowing/pom.xml, java/Windowing/src/main/java/com/amazonaws/services/msf/windowing/SlidingWindowStreamingJobWithParallelism.java
Added sliding window sample and changed README and pom.xml to accommodate sliding sample
=> Adding Sliding Window Sample

java/CustomMetrics/README.md, java/CustomMetrics/RecordCount/pom.xml, java/CustomMetrics/RecordCount/src/main/java/com/amazonaws/services/msf/RecordCountApplication.java, java/CustomMetrics/RecordCount/src/main/java/com/amazonaws/services/msf/RecordSchemaHelper.java, java/CustomMetrics/RecordCount/src/main/resources/flink-application-properties-dev.json, java/CustomMetrics/WordCount/pom.xml, java/CustomMetrics/WordCount/src/main/java/com/amazonaws/services/msf/WordCountApplication.java
Ported CustomMetrics code from old KDA repo to MSF repo. The current AWS documentation is broken - https://docs.aws.amazon.com/managed-flink/latest/java/monitoring-metrics-custom.html#monitoring-metrics-custom-examples-recordcount
=> Custommetrics

java/KafkaCustomKeystoreWithConfigProviders/README.md, java/KafkaCustomKeystoreWithConfigProviders/pom.xml
Fix missing local dependency in KafkaCustomKeystoreWithConfigProviders example
=> Fix missing local dependency in KafkaConfigProviders example

java/IcebergDatastreamSink/pom.xml, java/IcebergDatastreamSink/src/main/java/com/amazonaws/services/msf/JsonStringToGenericRecordMapFunction.java, java/IcebergDatastreamSink/src/main/java/com/amazonaws/services/msf/StreamingJob.java
=> updated iceberg sink

infrastructure/AutoScaling/README.md, infrastructure/AutoScaling/managed-flink-autoscaling.json
=> AutoScaling example parameters changes

infrastructure/ScheduledScaling/ScheduledScaling.template.json
=> fixed open policies

infrastructure/AutoScaling/README.md, infrastructure/AutoScaling/managed-flink-autoscaling.json
=> restricting policies and adding more metrics

README.md, infrastructure/README.md, python/README.md
Updates of example categories README to better explain the content
=> Minor updates of general READMEs

scala/GettingStarted/README.md
Fix description of required runtime properties and name of the JAR
=> Fix Scala Getting Started README

java/AsyncIO/README.md, java/AsyncIO/pom.xml, java/AsyncIO/src/main/java/com/amazonaws/services/msf/IncomingEvent.java, java/AsyncIO/src/main/java/com/amazonaws/services/msf/IncomingEventDataGeneratorFunction.java, java/AsyncIO/src/main/java/com/amazonaws/services/msf/ProcessedEvent.java, java/AsyncIO/src/main/java/com/amazonaws/services/msf/ProcessingFunction.java, java/AsyncIO/src/main/java/com/amazonaws/services/msf/RetriesFlinkJob.java, java/AsyncIO/src/main/resources/flink-application-properties-dev.json, java/AsyncIO/src/main/resources/lambda-cloudformation.yaml, java/AsyncIO/src/main/resources/launch-cfn.sh, java/AsyncIO/src/main/resources/log4j2.properties, java/SideOutputs/README.md, java/SideOutputs/pom.xml, java/SideOutputs/src/main/java/com/amazonaws/services/msf/IncomingEvent.java, java/SideOutputs/src/main/java/com/amazonaws/services/msf/IncomingEventDataGeneratorFunction.java, java/SideOutputs/src/main/java/com/amazonaws/services/msf/SideOutputsFlinkJob.java, java/SideOutputs/src/main/resources/flink-application-properties-dev.json, java/SideOutputs/src/main/resources/log4j2.properties
*Issue #, if available:* N/A
*Description of changes:* Adding new code examples for exception handling in flink applications. Specifically including examples of how to use Async I/O with retries and Side Outputs for splitting streams.
=> Java Examples for Exception Handling including Async IO and Side Ouputs

java/IcebergDatastreamSink/src/test/java/com/amazonaws/services/msf/datagen/AvroGenericStockTradeGeneratorFunctionTest.java
Fix wrong test in Iceberg DataStream API example
The change is verified by the test itself
=> Fix test in Iceberg DataStream example

java/PrometheusSink/README.md, java/PrometheusSink/pom.xml, java/PrometheusSink/src/main/java/com/amazonaws/services/msf/StreamingJob.java, java/PrometheusSink/src/main/java/com/amazonaws/services/msf/datagen/TemperatureSampleGeneratorFunction.java, java/PrometheusSink/src/main/java/com/amazonaws/services/msf/domain/TemperatureSample.java, java/PrometheusSink/src/main/java/com/amazonaws/services/msf/map/TemperatureSampleToPrometheusTimeSeriesMapper.java, java/PrometheusSink/src/main/resources/flink-application-properties-dev.json, java/PrometheusSink/src/main/resources/log4j2.properties, java/pom.xml
New example: Prometheus sink connector
* Tested on Managed Flink + AMP
=> New example: Prometheus sink

java/DynamoDBStreamSource/README.md, java/DynamoDBStreamSource/pom.xml, java/DynamoDBStreamSource/src/main/java/com/amazonaws/services/msf/ChangeEvent.java, java/DynamoDBStreamSource/src/main/java/com/amazonaws/services/msf/ChangeEventDeserializationSchema.java, java/DynamoDBStreamSource/src/main/java/com/amazonaws/services/msf/DdbTableItem.java, java/DynamoDBStreamSource/src/main/java/com/amazonaws/services/msf/StreamingJob.java, java/DynamoDBStreamSource/src/main/resources/flink-application-properties-dev.json, java/DynamoDBStreamSource/src/main/resources/log4j2.properties, java/pom.xml
Add example for using the DynamoDB Streams Source.
Verified that application runs locally and on MSF, and successfully prints output to logs.
=> Add example for DynamoDB Stream

python/PythonDependencies/README.md, python/PythonDependencies/main.py
Add clarifications about using Python dependencies defined via `requirements.txt`
No code changes
Only docs/comment changes
=> Add clarifications about where you can use Python dependencies

java/KinesisConnectors/README.md
* Explain how to configure Kinesis source and sink for cross-account access
Follow the instructions to configure cross-account
=> Explain Kinesis cross-account access

python/GettingStarted/README.md, python/GettingStarted/application_properties.json, python/GettingStarted/main.py, python/GettingStarted/pom.xml
Updated Python Getting Started to the latest Kinesis connector
1. tested locally in PyCharm
2. tested on Managed Flink
=> Update Python Getting Started to latest Kinesis connector

java/Iceberg/S3TableSink/README.md, java/Iceberg/S3TableSink/src/main/java/com/amazonaws/services/msf/StreamingJob.java, java/Iceberg/S3TableSink/src/main/java/com/amazonaws/services/msf/iceberg/IcebergSinkBuilder.java, java/Iceberg/S3TableSink/src/main/resources/flink-application-properties-dev.json
*For example: modify the Java Kinesis Sink to provide the stream ARN*
Please test your changes both running locally, in the IDE, and in Managed Service for Apache Flink. All examples must run
in both environment without code changes.
Describe how you tested your application, show the output of the running application with screenshots.
=> iceberg sink fix for s3table

java/Iceberg/IcebergDataStreamSink/README.md, java/Iceberg/IcebergDataStreamSink/pom.xml, java/Iceberg/IcebergDataStreamSink/src/main/java/com/amazonaws/services/msf/iceberg/IcebergSinkBuilder.java, java/Iceberg/IcebergDataStreamSink/src/main/resources/flink-application-properties-dev.json
*For example: modify the Java Kinesis Sink to provide the stream ARN*
Please test your changes both running locally, in the IDE, and in Managed Service for Apache Flink. All examples must run
in both environment without code changes.
Describe how you tested your application, show the output of the running application with screenshots.
=> update datastreamsink iceberg version

java/S3AvroSink/README.md, java/S3AvroSink/pom.xml, java/S3AvroSink/src/main/java/com/amazonaws/services/msf/StreamingJob.java, java/S3AvroSink/src/main/java/com/amazonaws/services/msf/datagen/StockPriceGeneratorFunction.java, java/S3AvroSink/src/main/resources/avro/stockprice.avdl, java/S3AvroSink/src/main/resources/flink-application-properties-dev.json, java/S3AvroSink/src/main/resources/log4j2.properties, java/S3AvroSource/README.md, java/S3AvroSource/pom.xml, java/S3AvroSource/src/main/java/com/amazonaws/services/msf/AvroSpecificRecordBulkFormat.java, java/S3AvroSource/src/main/java/com/amazonaws/services/msf/JsonConverter.java, java/S3AvroSource/src/main/java/com/amazonaws/services/msf/StreamingJob.java, java/S3AvroSource/src/main/resources/avro/stockprice.avdl, java/S3AvroSource/src/main/resources/flink-application-properties-dev.json, java/S3AvroSource/src/main/resources/log4j2.properties, java/pom.xml
New S3 AVRO source and sink examples
Run locally and on MSF
=> New examples: S3 AVRO Source and Sink

java/KinesisSourceDeaggregation/README.md, java/KinesisSourceDeaggregation/flink-app/README.md, java/KinesisSourceDeaggregation/flink-app/pom.xml, java/KinesisSourceDeaggregation/flink-app/src/main/java/com/amazonaws/services/msf/StreamingJob.java, java/KinesisSourceDeaggregation/flink-app/src/main/java/com/amazonaws/services/msf/deaggregation/KinesisDeaggregatingDeserializationSchemaWrapper.java, java/KinesisSourceDeaggregation/flink-app/src/main/java/com/amazonaws/services/msf/model/StockPrice.java, java/KinesisSourceDeaggregation/flink-app/src/main/resources/flink-application-properties-dev.json, java/KinesisSourceDeaggregation/flink-app/src/main/resources/log4j2.properties, java/KinesisSourceDeaggregation/kpl-producer/README.md, java/KinesisSourceDeaggregation/kpl-producer/pom.xml, java/KinesisSourceDeaggregation/kpl-producer/src/main/java/com/amazonaws/services/kds/producer/KplAggregatingProducer.java, java/KinesisSourceDeaggregation/kpl-producer/src/main/java/com/amazonaws/services/kds/producer/model/StockPrice.java, java/KinesisSourceDeaggregation/kpl-producer/src/main/resources/simplelogger.properties, java/KinesisSourceDeaggregation/pom.xml, java/pom.xml
Example demonstrating how to use a DeserializationSchema wrapper to implement de-aggregation in KinesisStreamSource
Tested locally and on MSF
=> Deaggregation with KinesisStreamSource

.gitattributes, .github/workflows/check-arns.yml, .gitignore
Add Github Action to bloc unmasked ARN
=> Add git filters

python/GettingStarted/README.md, python/GettingStarted/pom.xml
=> Fix typo in package name
